# spring配置
spring:
  redis:
    host: localhost
    port: 6379

# rocketmq配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: match_mq_producer_group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
    retry-next-server: true

# springdoc配置
springdoc:
  gatewayUrl: http://localhost:8080/${spring.application.name}
  api-docs:
    # 是否开启接口文档
    enabled: true
  info:
    # 标题
    title: '消息队列模块接口文档'
    # 描述
    description: '消息队列模块接口描述'
    # 作者信息
    contact:
      name: bruceXuu
      url: https://ruoyi.vip
